# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 907)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 3, 1, 1)
        self.label_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Status.setObjectName("label_Status")
        self.gridLayout.addWidget(self.label_Status, 9, 2, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_imgFormat = QtWidgets.QLabel(self.groupBox_11)
        self.label_imgFormat.setObjectName("label_imgFormat")
        self.gridLayout_13.addWidget(self.label_imgFormat, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_img_ny = QtWidgets.QLabel(self.groupBox_11)
        self.label_img_ny.setObjectName("label_img_ny")
        self.gridLayout_13.addWidget(self.label_img_ny, 1, 1, 1, 1)
        self.label_img_BitDepth = QtWidgets.QLabel(self.groupBox_11)
        self.label_img_BitDepth.setObjectName("label_img_BitDepth")
        self.gridLayout_13.addWidget(self.label_img_BitDepth, 3, 1, 1, 1)
        self.label_img_nx = QtWidgets.QLabel(self.groupBox_11)
        self.label_img_nx.setObjectName("label_img_nx")
        self.gridLayout_13.addWidget(self.label_img_nx, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_img_nz = QtWidgets.QLabel(self.groupBox_11)
        self.label_img_nz.setObjectName("label_img_nz")
        self.gridLayout_13.addWidget(self.label_img_nz, 2, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_11)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_layout_nx = QtWidgets.QLabel(self.groupBox_13)
        self.label_layout_nx.setObjectName("label_layout_nx")
        self.gridLayout_15.addWidget(self.label_layout_nx, 0, 2, 1, 1)
        self.label_layout_ny = QtWidgets.QLabel(self.groupBox_13)
        self.label_layout_ny.setObjectName("label_layout_ny")
        self.gridLayout_15.addWidget(self.label_layout_ny, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_13)
        self.label_11.setObjectName("label_11")
        self.gridLayout_15.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_13)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_13)
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_ScanByRows = QtWidgets.QLabel(self.groupBox_13)
        self.label_ScanByRows.setObjectName("label_ScanByRows")
        self.gridLayout_15.addWidget(self.label_ScanByRows, 2, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.plotWidget = mplwidget(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_10.addWidget(self.plotWidget, 1, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_SelectSubset = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_SelectSubset.setObjectName("pushButton_SelectSubset")
        self.gridLayout_14.addWidget(self.pushButton_SelectSubset, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_SubSet_x0 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_SubSet_x0.setObjectName("lineEdit_SubSet_x0")
        self.horizontalLayout.addWidget(self.lineEdit_SubSet_x0)
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_SubSet_dx = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_SubSet_dx.setObjectName("lineEdit_SubSet_dx")
        self.horizontalLayout.addWidget(self.lineEdit_SubSet_dx)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_12)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_SubSet_y0 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_SubSet_y0.setObjectName("lineEdit_SubSet_y0")
        self.horizontalLayout_2.addWidget(self.lineEdit_SubSet_y0)
        self.label_7 = QtWidgets.QLabel(self.groupBox_12)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_SubSet_dy = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_SubSet_dy.setObjectName("lineEdit_SubSet_dy")
        self.horizontalLayout_2.addWidget(self.lineEdit_SubSet_dy)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_14.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 4)
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.pushButton_convert_toTeraStitcher = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_convert_toTeraStitcher.setObjectName("pushButton_convert_toTeraStitcher")
        self.gridLayout_18.addWidget(self.pushButton_convert_toTeraStitcher, 5, 1, 1, 4)
        self.label_22 = QtWidgets.QLabel(self.groupBox_16)
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_16)
        self.label_8.setObjectName("label_8")
        self.gridLayout_18.addWidget(self.label_8, 2, 1, 1, 1)
        self.pushButton_selectFolder_toSave = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_selectFolder_toSave.setObjectName("pushButton_selectFolder_toSave")
        self.gridLayout_18.addWidget(self.pushButton_selectFolder_toSave, 3, 1, 1, 4)
        self.label_20 = QtWidgets.QLabel(self.groupBox_16)
        self.label_20.setObjectName("label_20")
        self.gridLayout_18.addWidget(self.label_20, 0, 1, 1, 1)
        self.lineEdit_scan_dy = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_scan_dy.setObjectName("lineEdit_scan_dy")
        self.gridLayout_18.addWidget(self.lineEdit_scan_dy, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_16)
        self.label_9.setObjectName("label_9")
        self.gridLayout_18.addWidget(self.label_9, 2, 3, 1, 1)
        self.lineEdit_SubSet_dz = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_SubSet_dz.setObjectName("lineEdit_SubSet_dz")
        self.gridLayout_18.addWidget(self.lineEdit_SubSet_dz, 2, 4, 1, 1)
        self.lineEdit_scan_dx = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_scan_dx.setObjectName("lineEdit_scan_dx")
        self.gridLayout_18.addWidget(self.lineEdit_scan_dx, 0, 2, 1, 1)
        self.pushButton_convert_toUnChunkedHDF5 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_convert_toUnChunkedHDF5.setObjectName("pushButton_convert_toUnChunkedHDF5")
        self.gridLayout_18.addWidget(self.pushButton_convert_toUnChunkedHDF5, 4, 1, 1, 4)
        self.lineEdit_SubSet_z0 = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_SubSet_z0.setObjectName("lineEdit_SubSet_z0")
        self.gridLayout_18.addWidget(self.lineEdit_SubSet_z0, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_16, 6, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_Folder = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_Folder.setObjectName("lineEdit_Folder")
        self.gridLayout_3.addWidget(self.lineEdit_Folder, 1, 1, 1, 1)
        self.lineEdit_File = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_File.setObjectName("lineEdit_File")
        self.gridLayout_3.addWidget(self.lineEdit_File, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_9)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.pushButton_OpenFile = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_OpenFile.setObjectName("pushButton_OpenFile")
        self.gridLayout_3.addWidget(self.pushButton_OpenFile, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.comboBox_Machine = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_Machine.setObjectName("comboBox_Machine")
        self.gridLayout_12.addWidget(self.comboBox_Machine, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_9, 1, 0, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_ChangeY_to_X = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_ChangeY_to_X.setObjectName("radioButton_ChangeY_to_X")
        self.gridLayout_5.addWidget(self.radioButton_ChangeY_to_X, 0, 0, 1, 1)
        self.radioButton_ChangeY_to_Y = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_ChangeY_to_Y.setObjectName("radioButton_ChangeY_to_Y")
        self.gridLayout_5.addWidget(self.radioButton_ChangeY_to_Y, 0, 1, 1, 1)
        self.radioButton_ChangeY_to_Z = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_ChangeY_to_Z.setObjectName("radioButton_ChangeY_to_Z")
        self.gridLayout_5.addWidget(self.radioButton_ChangeY_to_Z, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_ChangeX_to_X = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ChangeX_to_X.setObjectName("radioButton_ChangeX_to_X")
        self.gridLayout_4.addWidget(self.radioButton_ChangeX_to_X, 0, 0, 1, 1)
        self.radioButton_ChangeX_to_Y = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ChangeX_to_Y.setObjectName("radioButton_ChangeX_to_Y")
        self.gridLayout_4.addWidget(self.radioButton_ChangeX_to_Y, 0, 1, 1, 1)
        self.radioButton_ChangeX_to_Z = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ChangeX_to_Z.setObjectName("radioButton_ChangeX_to_Z")
        self.gridLayout_4.addWidget(self.radioButton_ChangeX_to_Z, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_ChangeZ_to_X = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ChangeZ_to_X.setObjectName("radioButton_ChangeZ_to_X")
        self.gridLayout_6.addWidget(self.radioButton_ChangeZ_to_X, 0, 0, 1, 1)
        self.radioButton_ChangeZ_to_Y = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ChangeZ_to_Y.setObjectName("radioButton_ChangeZ_to_Y")
        self.gridLayout_6.addWidget(self.radioButton_ChangeZ_to_Y, 0, 1, 1, 1)
        self.radioButton_ChangeZ_to_Z = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ChangeZ_to_Z.setObjectName("radioButton_ChangeZ_to_Z")
        self.gridLayout_6.addWidget(self.radioButton_ChangeZ_to_Z, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 1, 4, 3, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label = QtWidgets.QLabel(self.groupBox_18)
        self.label.setObjectName("label")
        self.gridLayout_21.addWidget(self.label, 1, 1, 1, 1)
        self.label_nProcess_Max = QtWidgets.QLabel(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nProcess_Max.sizePolicy().hasHeightForWidth())
        self.label_nProcess_Max.setSizePolicy(sizePolicy)
        self.label_nProcess_Max.setObjectName("label_nProcess_Max")
        self.gridLayout_21.addWidget(self.label_nProcess_Max, 1, 4, 1, 1)
        self.lineEdit_nProcesses = QtWidgets.QLineEdit(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nProcesses.sizePolicy().hasHeightForWidth())
        self.lineEdit_nProcesses.setSizePolicy(sizePolicy)
        self.lineEdit_nProcesses.setObjectName("lineEdit_nProcesses")
        self.gridLayout_21.addWidget(self.lineEdit_nProcesses, 2, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_18)
        self.label_24.setObjectName("label_24")
        self.gridLayout_21.addWidget(self.label_24, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_18)
        self.label_23.setObjectName("label_23")
        self.gridLayout_21.addWidget(self.label_23, 2, 1, 1, 1)
        self.lineEdit_nThreads = QtWidgets.QLineEdit(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nThreads.sizePolicy().hasHeightForWidth())
        self.lineEdit_nThreads.setSizePolicy(sizePolicy)
        self.lineEdit_nThreads.setObjectName("lineEdit_nThreads")
        self.gridLayout_21.addWidget(self.lineEdit_nThreads, 3, 4, 1, 1)
        self.radioButton_Sequential = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_Sequential.setObjectName("radioButton_Sequential")
        self.gridLayout_21.addWidget(self.radioButton_Sequential, 0, 1, 1, 1)
        self.radioButton_Parallel = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_Parallel.setObjectName("radioButton_Parallel")
        self.gridLayout_21.addWidget(self.radioButton_Parallel, 0, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_18, 1, 6, 3, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_FlipZ = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_FlipZ.setObjectName("checkBox_FlipZ")
        self.gridLayout_8.addWidget(self.checkBox_FlipZ, 5, 1, 1, 1)
        self.checkBox_FlipX = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_FlipX.setObjectName("checkBox_FlipX")
        self.gridLayout_8.addWidget(self.checkBox_FlipX, 3, 1, 1, 1)
        self.label_Extension = QtWidgets.QLabel(self.groupBox_6)
        self.label_Extension.setObjectName("label_Extension")
        self.gridLayout_8.addWidget(self.label_Extension, 1, 2, 1, 1)
        self.label_Y = QtWidgets.QLabel(self.groupBox_6)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_8.addWidget(self.label_Y, 4, 2, 1, 1)
        self.label_Channel = QtWidgets.QLabel(self.groupBox_6)
        self.label_Channel.setObjectName("label_Channel")
        self.gridLayout_8.addWidget(self.label_Channel, 2, 2, 1, 1)
        self.label_X = QtWidgets.QLabel(self.groupBox_6)
        self.label_X.setObjectName("label_X")
        self.gridLayout_8.addWidget(self.label_X, 3, 2, 1, 1)
        self.checkBox_FlipY = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_FlipY.setObjectName("checkBox_FlipY")
        self.gridLayout_8.addWidget(self.checkBox_FlipY, 4, 1, 1, 1)
        self.radioButton_X = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_X.setObjectName("radioButton_X")
        self.gridLayout_8.addWidget(self.radioButton_X, 3, 0, 1, 1)
        self.radioButton_Y = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_Y.setObjectName("radioButton_Y")
        self.gridLayout_8.addWidget(self.radioButton_Y, 4, 0, 1, 1)
        self.radioButton_Extension = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_Extension.setObjectName("radioButton_Extension")
        self.gridLayout_8.addWidget(self.radioButton_Extension, 1, 0, 1, 1)
        self.radioButton_Channel = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_Channel.setObjectName("radioButton_Channel")
        self.gridLayout_8.addWidget(self.radioButton_Channel, 2, 0, 1, 1)
        self.label_Z = QtWidgets.QLabel(self.groupBox_6)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_8.addWidget(self.label_Z, 5, 2, 1, 1)
        self.radioButton_Z = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_Z.setObjectName("radioButton_Z")
        self.gridLayout_8.addWidget(self.radioButton_Z, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 0, 3, 3)
        self.pushButton_Save = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout_2.addWidget(self.pushButton_Save, 5, 0, 1, 7)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.radioButton_ScanByRows = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_ScanByRows.setObjectName("radioButton_ScanByRows")
        self.gridLayout_16.addWidget(self.radioButton_ScanByRows, 0, 0, 1, 1)
        self.radioButton_ScanByColumns = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_ScanByColumns.setObjectName("radioButton_ScanByColumns")
        self.gridLayout_16.addWidget(self.radioButton_ScanByColumns, 0, 1, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_depthFormat_Stack = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_depthFormat_Stack.setObjectName("radioButton_depthFormat_Stack")
        self.gridLayout_7.addWidget(self.radioButton_depthFormat_Stack, 0, 1, 1, 1)
        self.radioButton_depthFormat_Slices = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_depthFormat_Slices.setObjectName("radioButton_depthFormat_Slices")
        self.gridLayout_7.addWidget(self.radioButton_depthFormat_Slices, 0, 2, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lineEdit_overlap = QtWidgets.QLineEdit(self.groupBox_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_overlap.sizePolicy().hasHeightForWidth())
        self.lineEdit_overlap.setSizePolicy(sizePolicy)
        self.lineEdit_overlap.setObjectName("lineEdit_overlap")
        self.gridLayout_20.addWidget(self.lineEdit_overlap, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_19, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_17, 1, 3, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.comboBox_16to8bit = QtWidgets.QComboBox(self.groupBox_20)
        self.comboBox_16to8bit.setObjectName("comboBox_16to8bit")
        self.comboBox_16to8bit.addItem("")
        self.comboBox_16to8bit.addItem("")
        self.comboBox_16to8bit.addItem("")
        self.comboBox_16to8bit.addItem("")
        self.comboBox_16to8bit.addItem("")
        self.comboBox_16to8bit.addItem("")
        self.comboBox_16to8bit.addItem("")
        self.gridLayout_22.addWidget(self.comboBox_16to8bit, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_22.addWidget(self.label_21, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_20, 1, 5, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 4)
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lineEdit_zSlide = QtWidgets.QLineEdit(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_zSlide.sizePolicy().hasHeightForWidth())
        self.lineEdit_zSlide.setSizePolicy(sizePolicy)
        self.lineEdit_zSlide.setObjectName("lineEdit_zSlide")
        self.gridLayout_17.addWidget(self.lineEdit_zSlide, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_15)
        self.label_18.setObjectName("label_18")
        self.gridLayout_17.addWidget(self.label_18, 0, 1, 1, 1)
        self.pushButton_ShowImages = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_ShowImages.setObjectName("pushButton_ShowImages")
        self.gridLayout_17.addWidget(self.pushButton_ShowImages, 4, 1, 1, 2)
        self.gridLayout.addWidget(self.groupBox_15, 6, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Status.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Image Metada"))
        self.label_16.setText(_translate("MainWindow", "Bit_Depth:"))
        self.label_15.setText(_translate("MainWindow", "img_ny:"))
        self.label_imgFormat.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "img_nx:"))
        self.label_img_ny.setText(_translate("MainWindow", "TextLabel"))
        self.label_img_BitDepth.setText(_translate("MainWindow", "TextLabel"))
        self.label_img_nx.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "img_format:"))
        self.label_19.setText(_translate("MainWindow", "img_nz"))
        self.label_img_nz.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_13.setTitle(_translate("MainWindow", "LayOut Metada"))
        self.label_layout_nx.setText(_translate("MainWindow", "TextLabel"))
        self.label_layout_ny.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "ny:"))
        self.label_10.setText(_translate("MainWindow", "nx:"))
        self.label_12.setText(_translate("MainWindow", "Scan by:"))
        self.label_ScanByRows.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Scanning LayOut"))
        self.groupBox_12.setTitle(_translate("MainWindow", "SubSet"))
        self.pushButton_SelectSubset.setText(_translate("MainWindow", "Save Subset LayOut"))
        self.label_4.setText(_translate("MainWindow", "x0"))
        self.label_6.setText(_translate("MainWindow", "dx"))
        self.label_5.setText(_translate("MainWindow", "y0"))
        self.label_7.setText(_translate("MainWindow", "dy"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Create TeraStitcher "))
        self.pushButton_convert_toTeraStitcher.setText(_translate("MainWindow", "Convert to TeraStitcher Format"))
        self.label_22.setText(_translate("MainWindow", "scan_dy (um)"))
        self.label_8.setText(_translate("MainWindow", "z0"))
        self.pushButton_selectFolder_toSave.setText(_translate("MainWindow", "Select Folder to Save"))
        self.label_20.setText(_translate("MainWindow", "scan_dx (um)"))
        self.label_9.setText(_translate("MainWindow", "dz"))
        self.pushButton_convert_toUnChunkedHDF5.setText(_translate("MainWindow", "Convert to Unchunked HDF5 Format"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Open Image"))
        self.label_2.setText(_translate("MainWindow", "File"))
        self.label_3.setText(_translate("MainWindow", "Folder"))
        self.pushButton_OpenFile.setText(_translate("MainWindow", "Open File"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Fluorescence Microscopy Machine"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Change Coordinates"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Y"))
        self.radioButton_ChangeY_to_X.setText(_translate("MainWindow", "X"))
        self.radioButton_ChangeY_to_Y.setText(_translate("MainWindow", "Y"))
        self.radioButton_ChangeY_to_Z.setText(_translate("MainWindow", "Z"))
        self.groupBox_2.setTitle(_translate("MainWindow", "X"))
        self.radioButton_ChangeX_to_X.setText(_translate("MainWindow", "X"))
        self.radioButton_ChangeX_to_Y.setText(_translate("MainWindow", "Y"))
        self.radioButton_ChangeX_to_Z.setText(_translate("MainWindow", "Z"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Z"))
        self.radioButton_ChangeZ_to_X.setText(_translate("MainWindow", "X"))
        self.radioButton_ChangeZ_to_Y.setText(_translate("MainWindow", "Y"))
        self.radioButton_ChangeZ_to_Z.setText(_translate("MainWindow", "Z"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Parallel Computing Settings"))
        self.label.setText(_translate("MainWindow", "nProcesses_Max:"))
        self.label_nProcess_Max.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "nThreads"))
        self.label_23.setText(_translate("MainWindow", "nProcesses"))
        self.radioButton_Sequential.setText(_translate("MainWindow", "Sequential"))
        self.radioButton_Parallel.setText(_translate("MainWindow", "Parallel"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Extract Scan Metada from File Name and Folder Name"))
        self.checkBox_FlipZ.setText(_translate("MainWindow", "Flip"))
        self.checkBox_FlipX.setText(_translate("MainWindow", "Flip"))
        self.label_Extension.setText(_translate("MainWindow", "TextLabel"))
        self.label_Y.setText(_translate("MainWindow", "TextLabel"))
        self.label_Channel.setText(_translate("MainWindow", "TextLabel"))
        self.label_X.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox_FlipY.setText(_translate("MainWindow", "Flip"))
        self.radioButton_X.setText(_translate("MainWindow", "X"))
        self.radioButton_Y.setText(_translate("MainWindow", "Y"))
        self.radioButton_Extension.setText(_translate("MainWindow", "Ending"))
        self.radioButton_Channel.setText(_translate("MainWindow", "Channel"))
        self.label_Z.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_Z.setText(_translate("MainWindow", "Z"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save Metada into a JSON File"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Scan Metadata"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Scanning by..."))
        self.radioButton_ScanByRows.setText(_translate("MainWindow", "Rows"))
        self.radioButton_ScanByColumns.setText(_translate("MainWindow", "Columns"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Image File Format"))
        self.radioButton_depthFormat_Stack.setText(_translate("MainWindow", "Stack"))
        self.radioButton_depthFormat_Slices.setText(_translate("MainWindow", "Slices"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Overalp (%)"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Processing Settings"))
        self.comboBox_16to8bit.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_16to8bit.setItemText(1, _translate("MainWindow", "img16to8_Linear"))
        self.comboBox_16to8bit.setItemText(2, _translate("MainWindow", "img16to8_Linear_Crop5to12"))
        self.comboBox_16to8bit.setItemText(3, _translate("MainWindow", "img16to8_Linear_CropMinMax"))
        self.comboBox_16to8bit.setItemText(4, _translate("MainWindow", "img16to8_HistEq"))
        self.comboBox_16to8bit.setItemText(5, _translate("MainWindow", "img16to8_CLAHE"))
        self.comboBox_16to8bit.setItemText(6, _translate("MainWindow", "wait_1sec"))
        self.label_21.setText(_translate("MainWindow", "Conversion Strategy: 16bit to 8bit"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Plot Image Tiles"))
        self.label_18.setText(_translate("MainWindow", "z slide"))
        self.pushButton_ShowImages.setText(_translate("MainWindow", "Show Images"))

from GUI.mplwidget import mplwidget
